# ===============================
#   Lychee Link Checker Config
# ===============================

# Nombre maximum de tentatives si un lien échoue
max_retries = 3

# Temps d’attente entre les tentatives (secondes)
retry_wait = 2

# Timeout maximum pour une requête (secondes)
timeout = 20

# User-Agent (certains sites bloquent les bots)
user_agent = "Mozilla/5.0 (compatible; IOBeats-LinkChecker/1.0; +https://iobeats.com)"

# Accepte certains codes HTTP qui sont souvent renvoyés par erreur
accept = [ "200..=299", "403", "429" ]

# Exclusions : liens connus comme instables ou qui bloquent les bots
exclude = [
  "^mailto:",                # emails
  "^tel:",                   # numéros de téléphone
  # Block explorers (souvent 403/429 à cause du rate-limit)
  "^https://(www\\.)?etherscan\\.io/address/0x[0-9a-fA-F]{40}",
  "^https://(www\\.)?bscscan\\.com/address/0x[0-9a-fA-F]{40}",
  "^https://(www\\.)?polygonscan\\.com/address/0x[0-9a-fA-F]{40}",
  "^https://(www\\.)?basescan\\.org/address/0x[0-9a-fA-F]{40}",
  "^https://(www\\.)?arbiscan\\.io/address/0x[0-9a-fA-F]{40}",
  # Raw GitHub (parfois bloque ou rate-limit)
  "^https://raw\\.githubusercontent\\.com/.*",
  # Badges (souvent redirigés ou variables)
  "^https://img\\.shields\\.io/.*",
  # Dashboards externes (souvent dynamiques)
  "^https://dune\\.com/.+"
]

# Active la vérification détaillée
verbose = true

# Pas de barre de progression dans GitHub Actions
no_progress = true

# Nombre maximum de redirections
max_redirects = 10
