# ==========================================
#  IO Beats — Config Lychee (exclusions optimisées)
# ==========================================

# Exclure tous les domaines IO Beats + block explorers
exclude = [
    ".*iobeats.com.*",   # Tous les domaines et sous-domaines IO Beats
    "https://etherscan.io",
    "https://bscscan.com",
    "https://polygonscan.com",
    "https://basescan.org",
    "https://arbiscan.io"
]

# Timeout en secondes (plus haut pour éviter timeouts sur gros sites)
timeout = 20

# Nombre max de redirections
max_redirects = 10

# Traiter 429 (Too Many Requests) comme valide
accept = [200, 201, 202, 203, 204, 205, 206, 429]

# Vérifier aussi les fichiers locaux (README, docs, etc.)
include = ["*.md"]

# Mode verbose activé pour logs clairs
verbose = true
