name: Dune — Ethereum

on:
  schedule:
    - cron: "6,36 * * * *"
  workflow_dispatch:

concurrency:
  group: treasury-dune-sync
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # ⬇️ Remplace par ta commande qui écrit data/dune/ethereum/latest.json
      - name: Run Dune query
        run: |
          mkdir -p data/dune/ethereum
          echo '{}' > data/dune/ethereum/latest.json  # placeholder

      - name: Commit & push results
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/dune/**/*.json || true
          git add data/dune/*.json || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(dune): update ethereum results"
          for i in 1 2 3 4 5; do
            git pull --rebase origin main || true
            if git push origin HEAD:main; then
              echo "Push OK (try $i)"; exit 0
            fi
            echo "Retry $i…"; sleep $((i*2))
          done
          echo "Push failed after retries"; exit 1
