name: Enforce single status label

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - name: Keep only the newly added status:* label
        uses: actions/github-script@v7
        with:
          script: |
            const added = context.payload.label?.name || "";
            // Ne faire quelque chose que si le label ajouté est de type "status:"
            if (!added.startsWith("status:")) {
              core.info(`Label "${added}" is not a status label. Skipping.`);
              return;
            }
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;

            // Récupère tous les labels de l'issue
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner, repo, issue_number
            });

            // Supprime tous les autres "status:*" sauf le label ajouté
            for (const l of labels) {
              if (l.name.startsWith("status:") && l.name !== added) {
                core.info(`Removing label: ${l.name}`);
                await github.rest.issues.removeLabel({
                  owner, repo, issue_number, name: l.name
                });
              }
            }

            core.info(`Kept label: ${added}`);
