name: Enforce single status label

on:
  issues:
    types: [opened, labeled, edited, reopened]
  pull_request:
    types: [opened, labeled, edited, reopened, synchronize]

permissions:
  issues: read
  pull-requests: read

jobs:
  require-status:
    runs-on: ubuntu-latest
    steps:
      - name: Require exactly one status label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            status:planned
            status:in-progress
            status:blocked
            status:done
