name: Docs — Link Checker

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.md"
      - "docs/**"
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee (link checker)
        uses: lycheeverse/lychee-action@v2
        with:
          # utilise la config ci-dessous
          args: >
            --config .lychee.toml
            --verbose
            --no-progress
            --accept 200,206,429
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
