name: Lint Links

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - ".lychee.toml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - ".lychee.toml"

jobs:
  lychee:
    runs-on: ubuntu-latest
    continue-on-error: true   # ✅ soft fail → n'arrête pas la CI si liens cassés
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >
            --verbose
            --no-progress
            --config .lychee.toml
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
