name: Docs — Markdown Lint

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - ".markdownlint.*"
  push:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - ".markdownlint.*"
  workflow_dispatch: {}

jobs:
  mdlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
